🌎 GPGN268 - Geophysical Data Analysis
- **Instructor:** Bia Villas Boas
- **TA:** James Clemson
## Lecture 19: Creating Xarray atasets
#### 🎯 Learning Objectives from this Lecture:
- Learn how to create well-formatted datasets from numpy arrays
- Lean how to save xarray datasets as netCDF files

Note: For this lecture, we will need to install the package `netcdf4` to our conda environment. `netcdf4` is one of a few packages (others are `scipy` and `h5netcdf`) that are used by xarray to read and write netcdf files.

In [3]:
import numpy as np
import xarray as xr

## A Comparison to Numpy

Remembering back to the Data Story 00 assignment, you looked at data for the maximum recorded temperature at the Denver Water Department for a number of years. You used numpy to load the dataset as an array, and performed operations like taking the mean and standard deviation on various axes of the data. Let's say we want to do this with xarray datasets instead of numpy arrays. We used `np.loadtxt()` to load the data as a numpy dataset, so lets try using the function we learned last lecture (`xr.load_dataset()`) to open the data as an xarray dataset.

In [4]:
xr.load_dataset('../assignments/intro-python/data/meteo_denver_tmax_2000_2022.txt')

ValueError: did not find a match in any of xarray's currently installed IO backends ['netcdf4']. Consider explicitly selecting one of the installed engines via the ``engine`` parameter, or installing additional IO dependencies, see:
https://docs.xarray.dev/en/stable/getting-started-guide/installing.html
https://docs.xarray.dev/en/stable/user-guide/io.html

Why didn't this command work? Because xarray uses the netCDF data format, which is a special way of encoding and saving data. NetCDF files are saved with the `.nc` extension. So xarray doesn't know what to do with a `.txt` file. If we want to make this data into an xarray dataset, we will need to do it ourselves.

## DataArrays

One of the simplest ways to make a numpy array is to create it from a list:

In [5]:
np.array([0,1,2])

array([0, 1, 2])

In the same way, we can make a DataArray from a numpy array using the command `xr.DataArray()`. If you recall from our last lecture, a data array takes a single numpy array and "wraps" it so we can using xarray dimensions and coordinates to access it. From the [xarray documentation](https://docs.xarray.dev/en/stable/generated/xarray.DataArray.html), we can see that `xr.DataArray()` takes several arguments. We will go over a few of them here, but as always, refer back to the documentation for a more complete description of the function.

First, let's load our maximum temperature data as a numpy array, and try converting it to a DataArray:

In [6]:
tmax_array = np.loadtxt('../assignments/intro-python/data/meteo_denver_tmax_2000_2022.txt')
tmax_array.shape # To remind us what tmax_array looks like

(23, 12)

In [7]:
tmax_dataArray1 = xr.DataArray(data=tmax_array)
tmax_dataArray1

<xarray.DataArray (dim_0: 23, dim_1: 12)> Size: 2kB
array([[50.9, 56.4, 57.5, 69.3, 78.2, 86. , 94.7, 93. , 81.9, 67.5, 46.2,
        46.1],
       [48.2, 45.4, 54.8, 65.8, 73.8, 87.3, 95.3, 90.6, 86. , 69.7, 61.7,
        50.2],
       [47.7, 51.8, 51.7, 69.7, 73.1, 90.4, 96. , 90.3, 82. , 63.3, 52.3,
        50.6],
       [54.7, 44.7, 54.6, 67.9, 73.8, 80.1, 96.7, 92.4, 79.3, 74.3, 51.4,
        50.2],
       [50.4, 46.5, 63.3, 63.5, 76.7, 80.8, 88.4, 85.9, 80.7, 67.4, 53.4,
        47.7],
       [49.2, 51.2, 55.4, 62.5, 73.8, 84.3, 95.8, 88.2, 83.7, 68.9, 60.3,
        45.2],
       [54.5, 47.8, 53.5, 68.9, 74.9, 87.1, 88. , 83.8, 72. , 60.8, 50. ,
        40.2],
       [30.6, 40.8, 58.5, 61.7, 72.5, 86.5, 92.2, 90.9, 79.5, 66.3, 53.8,
        38.9],
       [40.1, 48.6, 54.8, 63. , 72.5, 85. , 93.9, 86.7, 78.5, 67.7, 64.5,
        44.6],
       [52. , 56.5, 60.5, 61.2, 73.7, 80.6, 87. , 88.4, 79.7, 57.5, 59.5,
        41.3],
...
       [48.6, 46.6, 55.4, 58.3, 73.9, 89.1, 90. , 92.1, 81.9, 63.7, 57.8,
        46.2],
       [49.7, 46.3, 58.5, 66.2, 72.2, 85.1, 89.6, 86.7, 82.7, 73.7, 55.5,
        47.5],
       [48.4, 50. , 60.7, 65.6, 65.5, 86.7, 88.5, 91.2, 88.9, 72.3, 57.5,
        47.8],
       [50.9, 55.1, 58. , 63.1, 69.4, 89.2, 94.1, 89.6, 85. , 75.7, 64.1,
        45. ],
       [44.9, 56.1, 65.5, 65.4, 70.4, 88.1, 91.4, 87.8, 79.7, 66.7, 61.2,
        51.2],
       [51.5, 45.4, 58.8, 65.1, 76.8, 91.9, 92.2, 90.5, 86. , 64.2, 53.5,
        49. ],
       [47.9, 45.7, 53.4, 66.1, 65.8, 83.4, 94.6, 93. , 88.7, 61.9, 53.4,
        48.6],
       [50.2, 44.6, 58.1, 62.9, 77.2, 88.7, 92.8, 94.4, 82.1, 67.5, 61.6,
        49.6],
       [48.9, 42.6, 55.3, 60.7, 70.6, 89. , 93.1, 91.5, 87.5, 71.1, 62.1,
        56.7],
       [47.9, 46.2, 56. , 66.7, 74. , 87.1, 94.2, 92.3, 85.7, 69.5, 50.7,
        47.3]])
Dimensions without coordinates: dim_0, dim_1

Here we just specified the data argument of `xr.DataArray()`. We did successfully create a DataArray, but it doesn't have most of the things we like about dataArrays and datasets. The dimensions are just `dim_0` and `dim_1`, which doesn't tell us very much more than just using `axis=0` or `axis=1` in a numpy array. We also don't have and coordinates or indexes, so we still have to select our data using its raw position in the array. Finally, we aren't making use of the attributes to communicate more information about our data. In order to fix these, we will have to specify some other arguments of `xr.DataArray()`. Lets start by giving our DataArray some coordinates, corresponding to the months and years our data encompasses. Based on the documentation, we need to make a dictionary in the form `{'dimension_name':array}`.

In [8]:
months = np.array(['JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC'])
years = np.arange(2000, 2023)
tmax_dataArray2 = xr.DataArray(data=tmax_array, coords={'year':years, 'month':months})
tmax_dataArray2

<xarray.DataArray (year: 23, month: 12)> Size: 2kB
array([[50.9, 56.4, 57.5, 69.3, 78.2, 86. , 94.7, 93. , 81.9, 67.5, 46.2,
        46.1],
       [48.2, 45.4, 54.8, 65.8, 73.8, 87.3, 95.3, 90.6, 86. , 69.7, 61.7,
        50.2],
       [47.7, 51.8, 51.7, 69.7, 73.1, 90.4, 96. , 90.3, 82. , 63.3, 52.3,
        50.6],
       [54.7, 44.7, 54.6, 67.9, 73.8, 80.1, 96.7, 92.4, 79.3, 74.3, 51.4,
        50.2],
       [50.4, 46.5, 63.3, 63.5, 76.7, 80.8, 88.4, 85.9, 80.7, 67.4, 53.4,
        47.7],
       [49.2, 51.2, 55.4, 62.5, 73.8, 84.3, 95.8, 88.2, 83.7, 68.9, 60.3,
        45.2],
       [54.5, 47.8, 53.5, 68.9, 74.9, 87.1, 88. , 83.8, 72. , 60.8, 50. ,
        40.2],
       [30.6, 40.8, 58.5, 61.7, 72.5, 86.5, 92.2, 90.9, 79.5, 66.3, 53.8,
        38.9],
       [40.1, 48.6, 54.8, 63. , 72.5, 85. , 93.9, 86.7, 78.5, 67.7, 64.5,
        44.6],
       [52. , 56.5, 60.5, 61.2, 73.7, 80.6, 87. , 88.4, 79.7, 57.5, 59.5,
        41.3],
...
       [48.6, 46.6, 55.4, 58.3, 73.9, 89.1, 90. , 92.1, 81.9, 63.7, 57.8,
        46.2],
       [49.7, 46.3, 58.5, 66.2, 72.2, 85.1, 89.6, 86.7, 82.7, 73.7, 55.5,
        47.5],
       [48.4, 50. , 60.7, 65.6, 65.5, 86.7, 88.5, 91.2, 88.9, 72.3, 57.5,
        47.8],
       [50.9, 55.1, 58. , 63.1, 69.4, 89.2, 94.1, 89.6, 85. , 75.7, 64.1,
        45. ],
       [44.9, 56.1, 65.5, 65.4, 70.4, 88.1, 91.4, 87.8, 79.7, 66.7, 61.2,
        51.2],
       [51.5, 45.4, 58.8, 65.1, 76.8, 91.9, 92.2, 90.5, 86. , 64.2, 53.5,
        49. ],
       [47.9, 45.7, 53.4, 66.1, 65.8, 83.4, 94.6, 93. , 88.7, 61.9, 53.4,
        48.6],
       [50.2, 44.6, 58.1, 62.9, 77.2, 88.7, 92.8, 94.4, 82.1, 67.5, 61.6,
        49.6],
       [48.9, 42.6, 55.3, 60.7, 70.6, 89. , 93.1, 91.5, 87.5, 71.1, 62.1,
        56.7],
       [47.9, 46.2, 56. , 66.7, 74. , 87.1, 94.2, 92.3, 85.7, 69.5, 50.7,
        47.3]])
Coordinates:
  * year     (year) int64 184B 2000 2001 2002 2003 2004 ... 2019 2020 2021 2022
  * month    (month) <U3 144B 'JAN' 'FEB' 'MAR' 'APR' ... 'OCT' 'NOV' 'DEC'

In [9]:
tmax_dataArray2.sel(year=2013, month='MAR')

<xarray.DataArray ()> Size: 8B
array(55.4)
Coordinates:
    year     int64 8B 2013
    month    <U3 12B 'MAR'

In [10]:
tmax_dataArray2.mean(dim='year')

<xarray.DataArray (month: 12)> Size: 96B
array([48.46521739, 47.93913043, 57.72173913, 65.00869565, 72.70434783,
       86.58695652, 92.50869565, 90.35652174, 82.69130435, 67.76956522,
       56.75652174, 47.3826087 ])
Coordinates:
  * month    (month) <U3 144B 'JAN' 'FEB' 'MAR' 'APR' ... 'OCT' 'NOV' 'DEC'

This works well! We now have 2 labelled dimensions ("year" and "month") and corresponding indexes that we can use to select datapoints directly by their year and month. We can now do all of the data analysis operations (mean, median, standard deviation) by specifying named dimensions instead of axes, just like you saw in the previous lecture.
- **Note:** There are a lot of different ways to initialize coordinates and dimensions for DataArrays. This is the simplest and most common, where each dimension corresponds to a 1D coordinate array that is used to index your data (Like using x, y, and z values to pick a point in a mathematical function of the form f(x, y, z)). Xarray allows for the flexibility of providing coordinates that correspond to multiple dimensions, dimensions without coordinates, . . . to give more flexibility. We won't go over it here, but if you're curious, check out the documenation, scroll through some examples, and experiment a little to see just how much xarray is capable of.

The final thing we want to add is attributes, so that people can understand what our data means. We do this by passing a dictionary as the argument to `attrs`.

In [11]:
attrs_dict = {'title': 'Max Temperature at Denver Water Department', 'units': 'Degrees Farenheit', 'date_created': '2025-03-20',
              'description': 'Max temp by month and year from 2000 - 2022'}

tmax_dataArray3 = xr.DataArray(data=tmax_array, coords={'year':years, 'month':months}, attrs=attrs_dict)
tmax_dataArray3

<xarray.DataArray (year: 23, month: 12)> Size: 2kB
array([[50.9, 56.4, 57.5, 69.3, 78.2, 86. , 94.7, 93. , 81.9, 67.5, 46.2,
        46.1],
       [48.2, 45.4, 54.8, 65.8, 73.8, 87.3, 95.3, 90.6, 86. , 69.7, 61.7,
        50.2],
       [47.7, 51.8, 51.7, 69.7, 73.1, 90.4, 96. , 90.3, 82. , 63.3, 52.3,
        50.6],
       [54.7, 44.7, 54.6, 67.9, 73.8, 80.1, 96.7, 92.4, 79.3, 74.3, 51.4,
        50.2],
       [50.4, 46.5, 63.3, 63.5, 76.7, 80.8, 88.4, 85.9, 80.7, 67.4, 53.4,
        47.7],
       [49.2, 51.2, 55.4, 62.5, 73.8, 84.3, 95.8, 88.2, 83.7, 68.9, 60.3,
        45.2],
       [54.5, 47.8, 53.5, 68.9, 74.9, 87.1, 88. , 83.8, 72. , 60.8, 50. ,
        40.2],
       [30.6, 40.8, 58.5, 61.7, 72.5, 86.5, 92.2, 90.9, 79.5, 66.3, 53.8,
        38.9],
       [40.1, 48.6, 54.8, 63. , 72.5, 85. , 93.9, 86.7, 78.5, 67.7, 64.5,
        44.6],
       [52. , 56.5, 60.5, 61.2, 73.7, 80.6, 87. , 88.4, 79.7, 57.5, 59.5,
        41.3],
...
       [48.6, 46.6, 55.4, 58.3, 73.9, 89.1, 90. , 92.1, 81.9, 63.7, 57.8,
        46.2],
       [49.7, 46.3, 58.5, 66.2, 72.2, 85.1, 89.6, 86.7, 82.7, 73.7, 55.5,
        47.5],
       [48.4, 50. , 60.7, 65.6, 65.5, 86.7, 88.5, 91.2, 88.9, 72.3, 57.5,
        47.8],
       [50.9, 55.1, 58. , 63.1, 69.4, 89.2, 94.1, 89.6, 85. , 75.7, 64.1,
        45. ],
       [44.9, 56.1, 65.5, 65.4, 70.4, 88.1, 91.4, 87.8, 79.7, 66.7, 61.2,
        51.2],
       [51.5, 45.4, 58.8, 65.1, 76.8, 91.9, 92.2, 90.5, 86. , 64.2, 53.5,
        49. ],
       [47.9, 45.7, 53.4, 66.1, 65.8, 83.4, 94.6, 93. , 88.7, 61.9, 53.4,
        48.6],
       [50.2, 44.6, 58.1, 62.9, 77.2, 88.7, 92.8, 94.4, 82.1, 67.5, 61.6,
        49.6],
       [48.9, 42.6, 55.3, 60.7, 70.6, 89. , 93.1, 91.5, 87.5, 71.1, 62.1,
        56.7],
       [47.9, 46.2, 56. , 66.7, 74. , 87.1, 94.2, 92.3, 85.7, 69.5, 50.7,
        47.3]])
Coordinates:
  * year     (year) int64 184B 2000 2001 2002 2003 2004 ... 2019 2020 2021 2022
  * month    (month) <U3 144B 'JAN' 'FEB' 'MAR' 'APR' ... 'OCT' 'NOV' 'DEC'
Attributes:
    title:         Max Temperature at Denver Water Department
    units:         Degrees Farenheit
    date_created:  2025-03-20
    description:   Max temp by month and year from 2000 - 2022

We have now added attributes that explain what the data is, where it was collected, when the dataset was created, and what the units of our data are. This is very helpful when sharing data, since everything someone needs to understand data is included in the file itself. One last thing to highlight before we move on to Datasets is that we can also add attributes after the fact, using the structure shown below.

In [12]:
tmax_dataArray3.month.attrs['units'] = '3-letter code for months'
tmax_dataArray3

<xarray.DataArray (year: 23, month: 12)> Size: 2kB
array([[50.9, 56.4, 57.5, 69.3, 78.2, 86. , 94.7, 93. , 81.9, 67.5, 46.2,
        46.1],
       [48.2, 45.4, 54.8, 65.8, 73.8, 87.3, 95.3, 90.6, 86. , 69.7, 61.7,
        50.2],
       [47.7, 51.8, 51.7, 69.7, 73.1, 90.4, 96. , 90.3, 82. , 63.3, 52.3,
        50.6],
       [54.7, 44.7, 54.6, 67.9, 73.8, 80.1, 96.7, 92.4, 79.3, 74.3, 51.4,
        50.2],
       [50.4, 46.5, 63.3, 63.5, 76.7, 80.8, 88.4, 85.9, 80.7, 67.4, 53.4,
        47.7],
       [49.2, 51.2, 55.4, 62.5, 73.8, 84.3, 95.8, 88.2, 83.7, 68.9, 60.3,
        45.2],
       [54.5, 47.8, 53.5, 68.9, 74.9, 87.1, 88. , 83.8, 72. , 60.8, 50. ,
        40.2],
       [30.6, 40.8, 58.5, 61.7, 72.5, 86.5, 92.2, 90.9, 79.5, 66.3, 53.8,
        38.9],
       [40.1, 48.6, 54.8, 63. , 72.5, 85. , 93.9, 86.7, 78.5, 67.7, 64.5,
        44.6],
       [52. , 56.5, 60.5, 61.2, 73.7, 80.6, 87. , 88.4, 79.7, 57.5, 59.5,
        41.3],
...
       [48.6, 46.6, 55.4, 58.3, 73.9, 89.1, 90. , 92.1, 81.9, 63.7, 57.8,
        46.2],
       [49.7, 46.3, 58.5, 66.2, 72.2, 85.1, 89.6, 86.7, 82.7, 73.7, 55.5,
        47.5],
       [48.4, 50. , 60.7, 65.6, 65.5, 86.7, 88.5, 91.2, 88.9, 72.3, 57.5,
        47.8],
       [50.9, 55.1, 58. , 63.1, 69.4, 89.2, 94.1, 89.6, 85. , 75.7, 64.1,
        45. ],
       [44.9, 56.1, 65.5, 65.4, 70.4, 88.1, 91.4, 87.8, 79.7, 66.7, 61.2,
        51.2],
       [51.5, 45.4, 58.8, 65.1, 76.8, 91.9, 92.2, 90.5, 86. , 64.2, 53.5,
        49. ],
       [47.9, 45.7, 53.4, 66.1, 65.8, 83.4, 94.6, 93. , 88.7, 61.9, 53.4,
        48.6],
       [50.2, 44.6, 58.1, 62.9, 77.2, 88.7, 92.8, 94.4, 82.1, 67.5, 61.6,
        49.6],
       [48.9, 42.6, 55.3, 60.7, 70.6, 89. , 93.1, 91.5, 87.5, 71.1, 62.1,
        56.7],
       [47.9, 46.2, 56. , 66.7, 74. , 87.1, 94.2, 92.3, 85.7, 69.5, 50.7,
        47.3]])
Coordinates:
  * year     (year) int64 184B 2000 2001 2002 2003 2004 ... 2019 2020 2021 2022
  * month    (month) <U3 144B 'JAN' 'FEB' 'MAR' 'APR' ... 'OCT' 'NOV' 'DEC'
Attributes:
    title:         Max Temperature at Denver Water Department
    units:         Degrees Farenheit
    date_created:  2025-03-20
    description:   Max temp by month and year from 2000 - 2022

This structure also allows us to add attributes to specific variables or coordinates to add further clarification. In the example above, I added an attribute to the month coordinate specifically, to clarify that months were indexed as 3-letter strings.

## Datasets
If a DataArray corresponds to a single numpy array, a Dataset is a collection of several numpy arrays of the same shape. Datasets can store multiple variables that have the same dimensions and coordinates together. To explore how to create them, lets load a few more meteorological arrays:

In [13]:
precip_array = np.loadtxt('../assignments/intro-python/data/meteo_denver_precip_2000_2022.txt')
snow_array = np.loadtxt('../assignments/intro-python/data/meteo_denver_snow_2000_2022.txt')

As always, we follow the [xarray documentation for Datasets](https://docs.xarray.dev/en/stable/generated/xarray.Dataset.html). The simplest way to initialize a Dataset is to give it a few well-formatted DataArrays to stack together. To see this, lets turn our precipitation and snowfall into some well formated datarrays, and pass them to `xr.Dataset()` as data variables.

In [14]:
precip_attrs_dict = {'title': 'Precipitation at Denver Water Department', 'units': 'inches', 'date_created': '2025-03-20',
              'description': 'Precipitation by month and year from 2000 - 2022'}
precip_dataArray = xr.DataArray(data=precip_array, coords={'year':years, 'month':months}, attrs=precip_attrs_dict)

snow_attrs_dict = {'title': 'Snowfall at Denver Water Department', 'units': 'inches', 'date_created': '2025-03-20',
              'description': 'Total Snow Accumulation by month and year from 2000 - 2022'}
snow_dataArray = xr.DataArray(data=snow_array, coords={'year':years, 'month':months}, attrs=snow_attrs_dict)

meteo_ds1 = xr.Dataset(data_vars={'max_temp':tmax_dataArray3, 'precip':precip_dataArray, 'snow':snow_dataArray})
meteo_ds1

<xarray.Dataset> Size: 7kB
Dimensions:   (year: 23, month: 12)
Coordinates:
  * year      (year) int64 184B 2000 2001 2002 2003 2004 ... 2019 2020 2021 2022
  * month     (month) <U3 144B 'JAN' 'FEB' 'MAR' 'APR' ... 'OCT' 'NOV' 'DEC'
Data variables:
    max_temp  (year, month) float64 2kB 50.9 56.4 57.5 69.3 ... 69.5 50.7 47.3
    precip    (year, month) float64 2kB 0.5 0.27 1.47 1.28 ... 0.77 0.48 1.43
    snow      (year, month) float64 2kB 4.4 1.8 13.4 3.3 ... 0.0 -999.0 8.1 10.6

This works pretty well. Our dataset is well formatted, with "year" and "month" as indexed coordinates, and all of our DataArrays as variables. Xarray even kept our attributes, bundling them into each variable. However, creating DataArrays for each array, then using those DataArrays to make a Dataset is rather inefficient. By using a few more arguments of `xr.Dataset()`, we can do the whole thing in one go. To do this, we need to use `coords` as well as `data_vars`, and we need to be a little more sophisticated in how we input the arguments. In our previous example, we used xarray DataArrays. These DataArrays already have the information on which dimensions correspond to which axes and what coordinate to use to index each of those dimensions. When we use numpy arrays instead of premade DataArrays, we have to specify this to xarray manually.

- `data_vars`: We want to use the form `{'variable_name': (('dimension_names'), array)}`. This tells xarray what name to assign the array (variable_name), what the data values are (array), and which dimensions this array should be indexed by and in what order ('dimension_names').
- `coords`: We use the same general form of `{'coordinate_name': (('dimension_names'), array)}`. As before, this tells xarray what name to assign the array (coordinate_name), what the data values are (array), and which dimensions this array corresponds to and in what order ('dimension_names'). Oftentimes (unless you have multi-dimensional coordinates or a specific need), "coordinate_name" is the same as "dimension_name" and you only have a single dimension corresponding to a 1D arary.

Now, we apply this to our meteorological data:

In [15]:
meteo_ds2 = xr.Dataset(data_vars={'max_temp':(('year', 'month'), tmax_array),
                                  'precip':(('year', 'month'), precip_array),
                                  'snow':(('year', 'month'), snow_array)},
                       coords={'year':('year', years), 'month':('month', months)})
meteo_ds2

<xarray.Dataset> Size: 7kB
Dimensions:   (year: 23, month: 12)
Coordinates:
  * year      (year) int64 184B 2000 2001 2002 2003 2004 ... 2019 2020 2021 2022
  * month     (month) <U3 144B 'JAN' 'FEB' 'MAR' 'APR' ... 'OCT' 'NOV' 'DEC'
Data variables:
    max_temp  (year, month) float64 2kB 50.9 56.4 57.5 69.3 ... 69.5 50.7 47.3
    precip    (year, month) float64 2kB 0.5 0.27 1.47 1.28 ... 0.77 0.48 1.43
    snow      (year, month) float64 2kB 4.4 1.8 13.4 3.3 ... 0.0 -999.0 8.1 10.6

Success! We have managed to make the Dataset we wanted without having to first make DataArrays. The only thing we need to do now is add attributes, which we can do in exactly the same way as we did for DataArrays. We can use the `attrs` argument for global attributes, or assign attributes to individual variables and coordinates using the `ds['variable_name'].attrs['attribute_name'] = 'attribute_description'` format.

In [16]:
global_attrs = {'title': 'Meteorological Data from Denver Water Department',
                'description': 'Meteorological data by month and year from 2000 - 2022',
                'date_created': '2025-02-20'}

meteo_ds3 = xr.Dataset(data_vars={'max_temp':(('year', 'month'), tmax_array),
                                  'precip':(('year', 'month'), precip_array),
                                  'snow':(('year', 'month'), snow_array)},
                       coords={'year':('year', years), 'month':('month', months)}, attrs=global_attrs)

meteo_ds3['month'].attrs['units'] = '3-letter code for months'
meteo_ds3['max_temp'].attrs['units'] = 'Degrees Farenheit'
meteo_ds3['precip'].attrs['units'] = 'inches'
meteo_ds3['snow'].attrs['units'] = 'inches'

meteo_ds3

<xarray.Dataset> Size: 7kB
Dimensions:   (year: 23, month: 12)
Coordinates:
  * year      (year) int64 184B 2000 2001 2002 2003 2004 ... 2019 2020 2021 2022
  * month     (month) <U3 144B 'JAN' 'FEB' 'MAR' 'APR' ... 'OCT' 'NOV' 'DEC'
Data variables:
    max_temp  (year, month) float64 2kB 50.9 56.4 57.5 69.3 ... 69.5 50.7 47.3
    precip    (year, month) float64 2kB 0.5 0.27 1.47 1.28 ... 0.77 0.48 1.43
    snow      (year, month) float64 2kB 4.4 1.8 13.4 3.3 ... 0.0 -999.0 8.1 10.6
Attributes:
    title:         Meteorological Data from Denver Water Department
    description:   Meteorological data by month and year from 2000 - 2022
    date_created:  2025-02-20

## Saving DataArrays and Datasets
Now that we've created these nice DataArrays and Datasets, we want to save them. We can do this by saving them as netCDF files using the command `Dataset.to_netcdf()` or `DataArray.to_netcdf()`. Conveniently, both work in exactly the same way. From [the documentation](https://docs.xarray.dev/en/stable/generated/xarray.Dataset.to_netcdf.html#xarray.Dataset.to_netcdf), we can see that these functions take a lot of arguments. Fortunately, however, they are essentially all optional, and in most cases we don't need to worry about them. For now, let's just specify the path.

In [17]:
meteo_ds3.to_netcdf('den_water_dpt_meteo_data.nc')

Success! We have now created a new xarray dataset from numpy arrays and saved it to a file, so that we or anyone else can open it using xarray and have access to all of the features xarray offers.